/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Marina Savitzki
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_txt = new javax.swing.JLabel();
        id_tf = new javax.swing.JTextField();
        cliente_txt = new javax.swing.JLabel();
        cliente_cb = new javax.swing.JComboBox<>();
        servico_txt = new javax.swing.JLabel();
        servico_cb = new javax.swing.JComboBox<>();
        valor_txt = new javax.swing.JLabel();
        valor_ftf = new javax.swing.JFormattedTextField();
        data_txt = new javax.swing.JLabel();
        data_ftf = new javax.swing.JFormattedTextField();
        hora_ftf = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        hora_txt = new javax.swing.JLabel();
        id_txt1 = new javax.swing.JLabel();
        label_fundo_fosco = new javax.swing.JLabel();
        label_img_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_txt.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        id_txt.setForeground(new java.awt.Color(255, 255, 255));
        id_txt.setText("Observação");
        getContentPane().add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 140, 40));
        getContentPane().add(id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 260, 40));

        cliente_txt.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        cliente_txt.setForeground(new java.awt.Color(255, 255, 255));
        cliente_txt.setText("Cliente");
        getContentPane().add(cliente_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 90, 40));

        getContentPane().add(cliente_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 260, 40));

        servico_txt.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        servico_txt.setForeground(new java.awt.Color(255, 255, 255));
        servico_txt.setText("Serviço");
        getContentPane().add(servico_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 90, 40));

        getContentPane().add(servico_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 260, 40));

        valor_txt.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        valor_txt.setForeground(new java.awt.Color(255, 255, 255));
        valor_txt.setText("Valor R$");
        getContentPane().add(valor_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 90, 40));

        valor_ftf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_ftfActionPerformed(evt);
            }
        });
        getContentPane().add(valor_ftf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 260, 40));

        data_txt.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        data_txt.setForeground(new java.awt.Color(255, 255, 255));
        data_txt.setText("Data");
        getContentPane().add(data_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 90, 40));

        data_ftf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_ftfActionPerformed(evt);
            }
        });
        getContentPane().add(data_ftf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 260, 40));

        hora_ftf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_ftfActionPerformed(evt);
            }
        });
        getContentPane().add(hora_ftf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 260, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 570, 350));

        hora_txt.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        hora_txt.setForeground(new java.awt.Color(255, 255, 255));
        hora_txt.setText("Hora");
        getContentPane().add(hora_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 90, 40));

        id_txt1.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        id_txt1.setForeground(new java.awt.Color(255, 255, 255));
        id_txt1.setText("ID");
        getContentPane().add(id_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 90, 40));

        label_fundo_fosco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(label_fundo_fosco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label_img_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgendaFundo.png"))); // NOI18N
        getContentPane().add(label_img_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valor_ftfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_ftfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor_ftfActionPerformed

    private void data_ftfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_ftfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_ftfActionPerformed

    private void hora_ftfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora_ftfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora_ftfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cliente_cb;
    private javax.swing.JLabel cliente_txt;
    private javax.swing.JFormattedTextField data_ftf;
    private javax.swing.JLabel data_txt;
    private javax.swing.JFormattedTextField hora_ftf;
    private javax.swing.JLabel hora_txt;
    private javax.swing.JTextField id_tf;
    private javax.swing.JLabel id_txt;
    private javax.swing.JLabel id_txt1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label_fundo_fosco;
    private javax.swing.JLabel label_img_fundo;
    private javax.swing.JComboBox<String> servico_cb;
    private javax.swing.JLabel servico_txt;
    private javax.swing.JFormattedTextField valor_ftf;
    private javax.swing.JLabel valor_txt;
    // End of variables declaration//GEN-END:variables
}
