/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Marina Savitzki
 */
public class Agenda extends javax.swing.JDialog {

    private final AgendaController controller;
    /**
     * Creates new form AgendaDialog
     * @param parent
     * @param modal
     */
    public Agenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controller = new AgendaController(this);
        iniciar();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_tf = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        tituloTabelaTxt = new javax.swing.JLabel();
        id_txt1 = new javax.swing.JLabel();
        cliente_txt = new javax.swing.JLabel();
        cliente_cb = new javax.swing.JComboBox<>();
        servico_cb = new javax.swing.JComboBox<>();
        servico_txt = new javax.swing.JLabel();
        valor_txt = new javax.swing.JLabel();
        valorTf = new javax.swing.JTextField();
        dataFtf = new javax.swing.JFormattedTextField();
        data_txt = new javax.swing.JLabel();
        hora_txt = new javax.swing.JLabel();
        hora_ftf = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCliente_tb = new javax.swing.JTable();
        agendar_bt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        observTxtArea = new javax.swing.JTextArea();
        id_txt = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_tf.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 300, 40));

        cancelButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 340, 270, 50));

        tituloTabelaTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloTabelaTxt.setForeground(new java.awt.Color(204, 204, 204));
        tituloTabelaTxt.setText("Lista de agendamentos");
        getContentPane().add(tituloTabelaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 426, 980, 50));

        id_txt1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        id_txt1.setForeground(new java.awt.Color(204, 204, 204));
        id_txt1.setText("ID");
        getContentPane().add(id_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 90, 40));

        cliente_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        cliente_txt.setForeground(new java.awt.Color(204, 204, 204));
        cliente_txt.setText("Cliente");
        getContentPane().add(cliente_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, 40));

        cliente_cb.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(cliente_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 300, 40));

        servico_cb.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        servico_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                servico_cbItemStateChanged(evt);
            }
        });
        getContentPane().add(servico_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 300, 40));

        servico_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        servico_txt.setForeground(new java.awt.Color(204, 204, 204));
        servico_txt.setText("Serviço");
        getContentPane().add(servico_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 90, 40));

        valor_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        valor_txt.setForeground(new java.awt.Color(204, 204, 204));
        valor_txt.setText("Valor R$");
        getContentPane().add(valor_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 90, 40));

        valorTf.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(valorTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 300, 40));

        try {
            dataFtf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataFtf.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        dataFtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFtfActionPerformed(evt);
            }
        });
        getContentPane().add(dataFtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 300, 40));

        data_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        data_txt.setForeground(new java.awt.Color(204, 204, 204));
        data_txt.setText("Data");
        getContentPane().add(data_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 90, 40));

        hora_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        hora_txt.setForeground(new java.awt.Color(204, 204, 204));
        hora_txt.setText("Hora");
        getContentPane().add(hora_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 90, 40));

        try {
            hora_ftf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hora_ftf.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        hora_ftf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_ftfActionPerformed(evt);
            }
        });
        getContentPane().add(hora_ftf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 300, 40));

        listaCliente_tb.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        listaCliente_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaCliente_tb.setToolTipText("");
        jScrollPane2.setViewportView(listaCliente_tb);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 1260, 310));

        agendar_bt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        agendar_bt.setText("Agendar");
        agendar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendar_btActionPerformed(evt);
            }
        });
        getContentPane().add(agendar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 290, 50));

        observTxtArea.setColumns(20);
        observTxtArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        observTxtArea.setRows(5);
        jScrollPane1.setViewportView(observTxtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 590, 290));

        id_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        id_txt.setForeground(new java.awt.Color(204, 204, 204));
        id_txt.setText("Observação");
        getContentPane().add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 140, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseMaior.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void servico_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_servico_cbItemStateChanged
//        this.controller.refreshValue();
    }//GEN-LAST:event_servico_cbItemStateChanged

    private void dataFtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataFtfActionPerformed

    private void hora_ftfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora_ftfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora_ftfActionPerformed

    private void agendar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendar_btActionPerformed
        //        realiza o agendamento do cliente.
//        this.controller.schedule();
    }//GEN-LAST:event_agendar_btActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
/**
 * botao cancelar da view agenda
 * 
 * 
 */
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Agenda dialog = new Agenda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendar_bt;
    private javax.swing.JLabel bg;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cliente_cb;
    private javax.swing.JLabel cliente_txt;
    private javax.swing.JFormattedTextField dataFtf;
    private javax.swing.JLabel data_txt;
    private javax.swing.JFormattedTextField hora_ftf;
    private javax.swing.JLabel hora_txt;
    private javax.swing.JTextField id_tf;
    private javax.swing.JLabel id_txt;
    private javax.swing.JLabel id_txt1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listaCliente_tb;
    private javax.swing.JTextArea observTxtArea;
    private javax.swing.JComboBox<String> servico_cb;
    private javax.swing.JLabel servico_txt;
    private javax.swing.JLabel tituloTabelaTxt;
    private javax.swing.JTextField valorTf;
    private javax.swing.JLabel valor_txt;
    // End of variables declaration//GEN-END:variables
  private void iniciar() {
        this.controller.refreshTable();
        this.controller.refreshClient();
        this.controller.refreshService();
        this.controller.refreshValue();
    }

    public JTable getListaCliente_tb() {
        return listaCliente_tb;
    }

    public void setListaCliente_tb(JTable listaCliente_tb) {
        this.listaCliente_tb = listaCliente_tb;
    }

    public JComboBox<String> getCliente_cb() {
        return cliente_cb;
    }

    public void setCliente_cb(JComboBox<String> cliente_cb) {
        this.cliente_cb = cliente_cb;
    }

    public JComboBox<String> getServico_cb() {
        return servico_cb;
    }

    public void setServico_cb(JComboBox<String> servico_cb) {
        this.servico_cb = servico_cb;
    }

    public JTextField getValorTf() {
        return valorTf;
    }

    public void setValorTf(JTextField valorTf) {
        this.valorTf = valorTf;
    }

    public JFormattedTextField getHora_ftf() {
        return hora_ftf;
    }

    public void setHora_ftf(JFormattedTextField hora_ftf) {
        this.hora_ftf = hora_ftf;
    }

    public JTextField getId_tf() {
        return id_tf;
    }

    public void setId_tf(JTextField id_tf) {
        this.id_tf = id_tf;
    }

    public JFormattedTextField getDataFtf() {
        return dataFtf;
    }

    public void setDataFtf(JFormattedTextField dataFtf) {
        this.dataFtf = dataFtf;
    }

    public JTextArea getObservTxtArea() {
        return observTxtArea;
    }

    public void setObservTxtArea(JTextArea observTxtArea) {
        this.observTxtArea = observTxtArea;
    }
    
}

