package view;

import controller.MenuController;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import javax.swing.JComponent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.MenuElement;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 *
 * @author Marina Savitzki
 */
public class Menu extends javax.swing.JFrame {

    private final MenuController controller;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
//        iniciar a tela principal maximizada
        setExtendedState(MAXIMIZED_BOTH);
        customizeMenuBar(menuBar);
        this.controller = new MenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCliente_tb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        logOff_bt = new javax.swing.JLabel();
        userTxt = new javax.swing.JLabel();
        userLogin = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        cadastroMenu = new javax.swing.JMenu();
        jMenuItem_cliente = new javax.swing.JMenuItem();
        jMenuItem_servico = new javax.swing.JMenuItem();
        jMenuItem_usuario = new javax.swing.JMenuItem();
        operacaoMenu = new javax.swing.JMenu();
        agendaItemMenu = new javax.swing.JMenuItem();
        relatorioMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-alterar-24.png"))); // NOI18N
        updateButton.setText("Alterar");
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 780, 270, 50));

        deleteButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-excluir-24.png"))); // NOI18N
        deleteButton.setText("Excluir");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 780, 270, 50));

        newButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-soma-24.png"))); // NOI18N
        newButton.setText("Novo");
        newButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 780, 270, 50));

        listaCliente_tb.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        listaCliente_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listaCliente_tb);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 1210, 630));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agendamentos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 960, 50));

        footer.setBackground(new java.awt.Color(164, 164, 164));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logOff_bt.setBackground(new java.awt.Color(255, 255, 255));
        logOff_bt.setForeground(new java.awt.Color(255, 255, 255));
        logOff_bt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOff_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-logout-arredondado-para-baixo-24.png"))); // NOI18N
        logOff_bt.setToolTipText("LogOff");
        logOff_bt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logOff_bt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOff_bt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOff_btMouseClicked(evt);
            }
        });
        footer.add(logOff_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 60, 80));

        userTxt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userTxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-usuário-verificado-masculino-24.png"))); // NOI18N
        userTxt.setText("Usuário autenticado: ");
        footer.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 80));

        userLogin.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userLogin.setForeground(new java.awt.Color(255, 255, 255));
        userLogin.setText("Barbeiro");
        footer.add(userLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 340, 80));

        getContentPane().add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 910, 1950, 100));

        bg.setBackground(new java.awt.Color(233, 118, 45));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu.png"))); // NOI18N
        bg.setText(" ");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -70, 1990, -1));

        menuBar.setFont(new java.awt.Font("Buxton Sketch", 0, 24)); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(235, 40));

        cadastroMenu.setText("Cadastro");
        cadastroMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        cadastroMenu.setPreferredSize(new java.awt.Dimension(100, 24));

        jMenuItem_cliente.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jMenuItem_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/cliente-icon.png"))); // NOI18N
        jMenuItem_cliente.setText("Cliente");
        jMenuItem_cliente.setPreferredSize(new java.awt.Dimension(120, 30));
        jMenuItem_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_clienteActionPerformed(evt);
            }
        });
        cadastroMenu.add(jMenuItem_cliente);

        jMenuItem_servico.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jMenuItem_servico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/tesoura-icon.png"))); // NOI18N
        jMenuItem_servico.setText("Serviço");
        jMenuItem_servico.setPreferredSize(new java.awt.Dimension(120, 30));
        cadastroMenu.add(jMenuItem_servico);

        jMenuItem_usuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jMenuItem_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/usuario-icon.png"))); // NOI18N
        jMenuItem_usuario.setText("Usuário");
        jMenuItem_usuario.setPreferredSize(new java.awt.Dimension(120, 30));
        cadastroMenu.add(jMenuItem_usuario);

        menuBar.add(cadastroMenu);

        operacaoMenu.setText("Operação");
        operacaoMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        operacaoMenu.setPreferredSize(new java.awt.Dimension(100, 24));

        agendaItemMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        agendaItemMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/agenda-icon.png"))); // NOI18N
        agendaItemMenu.setText("Agenda");
        agendaItemMenu.setPreferredSize(new java.awt.Dimension(120, 30));
        agendaItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaItemMenuActionPerformed(evt);
            }
        });
        operacaoMenu.add(agendaItemMenu);

        menuBar.add(operacaoMenu);

        relatorioMenu.setText("Relatório");
        relatorioMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        relatorioMenu.setPreferredSize(new java.awt.Dimension(100, 24));
        menuBar.add(relatorioMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_clienteActionPerformed

    private void agendaItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaItemMenuActionPerformed
        controller.goAgenda();
    }//GEN-LAST:event_agendaItemMenuActionPerformed

    private void logOff_btMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOff_btMouseClicked
       /**
        * Deslogar usuario
        * voltar para a tela de login
        * fechar a tela principal
        */
    }//GEN-LAST:event_logOff_btMouseClicked

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
       controller.goAgenda();
    }//GEN-LAST:event_newButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agendaItemMenu;
    private javax.swing.JLabel bg;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem_cliente;
    private javax.swing.JMenuItem jMenuItem_servico;
    private javax.swing.JMenuItem jMenuItem_usuario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listaCliente_tb;
    private javax.swing.JLabel logOff_bt;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton newButton;
    private javax.swing.JMenu operacaoMenu;
    private javax.swing.JMenu relatorioMenu;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userLogin;
    private javax.swing.JLabel userTxt;
    // End of variables declaration//GEN-END:variables


    private void customizeMenuBar(JMenuBar menuBar) {

    menuBar.setUI(new BasicMenuBarUI() {

        @Override
        public void paint(Graphics g, JComponent c) {
            g.setColor(Color.black);
            g.fillRect(0, 0, c.getWidth(), c.getHeight());
        }

    });

    MenuElement[] menus = menuBar.getSubElements();

    for (MenuElement menuElement : menus) {

        JMenu menu = (JMenu) menuElement.getComponent();
        changeComponentColors(menu);
        menu.setOpaque(true);

        MenuElement[] menuElements = menu.getSubElements();

        for (MenuElement popupMenuElement : menuElements) {

            JPopupMenu popupMenu = (JPopupMenu) popupMenuElement.getComponent();
            popupMenu.setBorder(null);

            MenuElement[] menuItens = popupMenuElement.getSubElements();

            for (MenuElement menuItemElement : menuItens) {

                JMenuItem menuItem = (JMenuItem) menuItemElement.getComponent();
                changeComponentColors(menuItem);
                menuItem.setOpaque(true);

            }
        }
    }
}

private void changeComponentColors(Component comp) {
    comp.setBackground(Color.black);
    comp.setForeground(Color.white);
}
    
}
