package view;

import controller.MenuController;

/**
 *
 * @author Marina Savitzki
 */
public class Menu extends javax.swing.JFrame {

    private final MenuController controller;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
//        iniciar a tela principal maximizada
        setExtendedState(MAXIMIZED_BOTH);
        this.controller = new MenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        cadastroMenu = new javax.swing.JMenu();
        jMenuItem_cliente = new javax.swing.JMenuItem();
        jMenuItem_servico = new javax.swing.JMenuItem();
        jMenuItem_usuario = new javax.swing.JMenuItem();
        operacaoMenu = new javax.swing.JMenu();
        agendaItemMenu = new javax.swing.JMenuItem();
        relatorioMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Prancheta 2.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        menuBar.setFont(new java.awt.Font("Buxton Sketch", 0, 24)); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(235, 40));

        cadastroMenu.setText("Cadastro");
        cadastroMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        cadastroMenu.setPreferredSize(new java.awt.Dimension(100, 24));

        jMenuItem_cliente.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jMenuItem_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/cliente-icon.png"))); // NOI18N
        jMenuItem_cliente.setText("Cliente");
        jMenuItem_cliente.setPreferredSize(new java.awt.Dimension(120, 30));
        jMenuItem_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_clienteActionPerformed(evt);
            }
        });
        cadastroMenu.add(jMenuItem_cliente);

        jMenuItem_servico.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jMenuItem_servico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/tesoura-icon.png"))); // NOI18N
        jMenuItem_servico.setText("Serviço");
        jMenuItem_servico.setPreferredSize(new java.awt.Dimension(120, 30));
        cadastroMenu.add(jMenuItem_servico);

        jMenuItem_usuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jMenuItem_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/usuario-icon.png"))); // NOI18N
        jMenuItem_usuario.setText("Usuário");
        jMenuItem_usuario.setPreferredSize(new java.awt.Dimension(120, 30));
        cadastroMenu.add(jMenuItem_usuario);

        menuBar.add(cadastroMenu);

        operacaoMenu.setText("Operação");
        operacaoMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        operacaoMenu.setPreferredSize(new java.awt.Dimension(100, 24));

        agendaItemMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        agendaItemMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/agenda-icon.png"))); // NOI18N
        agendaItemMenu.setText("Agenda");
        agendaItemMenu.setPreferredSize(new java.awt.Dimension(120, 30));
        agendaItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaItemMenuActionPerformed(evt);
            }
        });
        operacaoMenu.add(agendaItemMenu);

        menuBar.add(operacaoMenu);

        relatorioMenu.setText("Relatório");
        relatorioMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        relatorioMenu.setPreferredSize(new java.awt.Dimension(100, 24));
        menuBar.add(relatorioMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_clienteActionPerformed

    private void agendaItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaItemMenuActionPerformed
        controller.goAgenda();
    }//GEN-LAST:event_agendaItemMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agendaItemMenu;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem_cliente;
    private javax.swing.JMenuItem jMenuItem_servico;
    private javax.swing.JMenuItem jMenuItem_usuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu operacaoMenu;
    private javax.swing.JMenu relatorioMenu;
    // End of variables declaration//GEN-END:variables
}
