package view;

import controller.MenuTesteController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Marina Savitzki
 */
public class MenuTeste extends javax.swing.JFrame {

    private final MenuTesteController controller;

    /**
     * Creates new form MenuTeste
     */
    public MenuTeste() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.controller = new MenuTesteController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        center = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        agendamentoTxt = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCliente_tb = new javax.swing.JTable();
        bg_main = new javax.swing.JLabel();
        agenda = new javax.swing.JPanel();
        id_tf = new javax.swing.JTextField();
        cliente_cb = new javax.swing.JComboBox<>();
        servico_cb = new javax.swing.JComboBox<>();
        valorTf = new javax.swing.JTextField();
        dataFtf = new javax.swing.JFormattedTextField();
        hora_ftf = new javax.swing.JFormattedTextField();
        hora_txt = new javax.swing.JLabel();
        data_txt = new javax.swing.JLabel();
        valor_txt = new javax.swing.JLabel();
        servico_txt = new javax.swing.JLabel();
        cliente_txt = new javax.swing.JLabel();
        id_txt1 = new javax.swing.JLabel();
        id_txt = new javax.swing.JLabel();
        cancelButtonAgenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        observTxtArea = new javax.swing.JTextArea();
        agendar_bt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCliente_tb1 = new javax.swing.JTable();
        tituloTabelaTxt = new javax.swing.JLabel();
        bg_main1 = new javax.swing.JLabel();
        users = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        listUsers = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        newUserButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        updateUserButton = new javax.swing.JButton();
        bg_main2 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutButtonFooter = new javax.swing.JButton();
        exitButtonFooter = new javax.swing.JButton();
        bg_footer = new javax.swing.JLabel();
        left = new javax.swing.JPanel();
        gerenciaTxt = new javax.swing.JLabel();
        clientButton = new javax.swing.JButton();
        serviceButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        financesButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();
        bg_left = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1980, 1080));
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(1980, 1060));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        center.setBackground(new java.awt.Color(200, 200, 200));
        center.setLayout(new javax.swing.BoxLayout(center, javax.swing.BoxLayout.LINE_AXIS));

        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agendamentoTxt.setBackground(new java.awt.Color(51, 51, 51));
        agendamentoTxt.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        agendamentoTxt.setForeground(new java.awt.Color(51, 51, 51));
        agendamentoTxt.setText("Agendamentos");
        main.add(agendamentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1230, 50));

        newButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        newButton.setForeground(new java.awt.Color(51, 51, 51));
        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-soma-24.png"))); // NOI18N
        newButton.setText("Novo");
        newButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        main.add(newButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 880, 270, 50));

        listaCliente_tb.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        listaCliente_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Hora", "Data do agendamento", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listaCliente_tb);

        main.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 1520, 760));

        bg_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseSemCor.png"))); // NOI18N
        main.add(bg_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 960));

        center.add(main);

        agenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_tf.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        agenda.add(id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, 40));

        cliente_cb.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        agenda.add(cliente_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 490, 40));

        servico_cb.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        servico_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                servico_cbItemStateChanged(evt);
            }
        });
        agenda.add(servico_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 490, 40));

        valorTf.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        agenda.add(valorTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 140, 40));

        try {
            dataFtf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataFtf.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        dataFtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFtfActionPerformed(evt);
            }
        });
        agenda.add(dataFtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 140, 40));

        try {
            hora_ftf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hora_ftf.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        hora_ftf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_ftfActionPerformed(evt);
            }
        });
        agenda.add(hora_ftf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 140, 40));

        hora_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        hora_txt.setForeground(new java.awt.Color(51, 51, 51));
        hora_txt.setText("Hora");
        agenda.add(hora_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, 40));

        data_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        data_txt.setForeground(new java.awt.Color(51, 51, 51));
        data_txt.setText("Data");
        agenda.add(data_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, 40));

        valor_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        valor_txt.setForeground(new java.awt.Color(51, 51, 51));
        valor_txt.setText("Valor R$");
        agenda.add(valor_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 90, 40));

        servico_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        servico_txt.setForeground(new java.awt.Color(51, 51, 51));
        servico_txt.setText("Serviço");
        agenda.add(servico_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 90, 40));

        cliente_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        cliente_txt.setForeground(new java.awt.Color(51, 51, 51));
        cliente_txt.setText("Cliente");
        agenda.add(cliente_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, 40));

        id_txt1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        id_txt1.setForeground(new java.awt.Color(51, 51, 51));
        id_txt1.setText("ID");
        agenda.add(id_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, 40));

        id_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        id_txt.setForeground(new java.awt.Color(51, 51, 51));
        id_txt.setText("Observação");
        agenda.add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 140, 40));

        cancelButtonAgenda.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        cancelButtonAgenda.setText("Cancelar");
        cancelButtonAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonAgendaActionPerformed(evt);
            }
        });
        agenda.add(cancelButtonAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 880, 270, 50));

        observTxtArea.setColumns(20);
        observTxtArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        observTxtArea.setRows(5);
        jScrollPane1.setViewportView(observTxtArea);

        agenda.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 730, 350));

        agendar_bt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        agendar_bt.setText("Agendar");
        agendar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendar_btActionPerformed(evt);
            }
        });
        agenda.add(agendar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 880, 290, 50));

        listaCliente_tb1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        listaCliente_tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaCliente_tb1.setToolTipText("");
        jScrollPane3.setViewportView(listaCliente_tb1);

        agenda.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 1530, 310));

        tituloTabelaTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloTabelaTxt.setForeground(new java.awt.Color(51, 51, 51));
        tituloTabelaTxt.setText("Lista de agendamentos");
        agenda.add(tituloTabelaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 980, 50));

        bg_main1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseSemCor.png"))); // NOI18N
        agenda.add(bg_main1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 960));

        center.add(agenda);

        users.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(204, 204, 204));
        title.setText("Usuários cadastrados");
        users.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 640, 40));

        jTable1.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuário", "Nível de acesso", "Data cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listUsers.setViewportView(jTable1);

        users.add(listUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 800, 700));

        newUserButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        newUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-soma-24.png"))); // NOI18N
        newUserButton.setText("Novo");
        newUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserButtonActionPerformed(evt);
            }
        });
        users.add(newUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 860, 200, 50));

        deleteUserButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        deleteUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-excluir-24 (2).png"))); // NOI18N
        deleteUserButton.setText("Excluir");
        deleteUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        users.add(deleteUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 860, 200, 50));

        updateUserButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        updateUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-alterar-24.png"))); // NOI18N
        updateUserButton.setText("Alterar");
        updateUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        users.add(updateUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 860, 200, 50));

        bg_main2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseSemCor.png"))); // NOI18N
        users.add(bg_main2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 960));

        center.add(users);

        getContentPane().add(center, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1660, 960));

        footer.setBackground(new java.awt.Color(255, 255, 255));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("user login");
        footer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 270, 40));

        logoutButtonFooter.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        logoutButtonFooter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-logout-arredondado-para-baixo-24.png"))); // NOI18N
        logoutButtonFooter.setText("Logout");
        footer.add(logoutButtonFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 20, 130, 40));

        exitButtonFooter.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        exitButtonFooter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-sair-24.png"))); // NOI18N
        exitButtonFooter.setText("Sair");
        exitButtonFooter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonFooterActionPerformed(evt);
            }
        });
        footer.add(exitButtonFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1770, 20, 130, 40));

        bg_footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/footer.png"))); // NOI18N
        bg_footer.setText("jLabel1");
        footer.add(bg_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1980, 120));

        getContentPane().add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 960, 1980, 130));

        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gerenciaTxt.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        gerenciaTxt.setForeground(new java.awt.Color(255, 255, 255));
        gerenciaTxt.setText("Gerenciamento");
        left.add(gerenciaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 50));

        clientButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        clientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/grupo-de-usuário24.png"))); // NOI18N
        clientButton.setText("Cliente");
        clientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });
        left.add(clientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 50));

        serviceButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        serviceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-serviço-24.png"))); // NOI18N
        serviceButton.setText("Serviço");
        serviceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceButtonActionPerformed(evt);
            }
        });
        left.add(serviceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 280, 50));

        userButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-usuário-16.png"))); // NOI18N
        userButton.setText("Usuário");
        userButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        left.add(userButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 280, 50));

        financesButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        financesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-dinheiro-24.png"))); // NOI18N
        financesButton.setText("Finanças");
        financesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        financesButton.setEnabled(false);
        financesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financesButtonActionPerformed(evt);
            }
        });
        left.add(financesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 280, 50));

        reportButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        reportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/relatorioTrabalho24-icon.png"))); // NOI18N
        reportButton.setText("Relatório");
        reportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });
        left.add(reportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 280, 50));

        bg_left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lateral.png"))); // NOI18N
        left.add(bg_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 970));

        getContentPane().add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 320, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientButtonActionPerformed

    private void serviceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
         this.controller.actionPerformed(evt);
    }//GEN-LAST:event_userButtonActionPerformed

    private void financesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_financesButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        this.controller.actionPerformed(evt);
    }//GEN-LAST:event_newButtonActionPerformed

    private void servico_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_servico_cbItemStateChanged
        //        this.controller.refreshValue();
    }//GEN-LAST:event_servico_cbItemStateChanged

    private void dataFtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataFtfActionPerformed

    private void hora_ftfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora_ftfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora_ftfActionPerformed

    private void agendar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendar_btActionPerformed
        this.controller.actionPerformed(evt);
    }//GEN-LAST:event_agendar_btActionPerformed

    private void cancelButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonAgendaActionPerformed
        this.controller.actionPerformed(evt);
    }//GEN-LAST:event_cancelButtonAgendaActionPerformed

    private void exitButtonFooterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonFooterActionPerformed
        this.controller.actionPerformed(evt);
    }//GEN-LAST:event_exitButtonFooterActionPerformed

    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserButtonActionPerformed
        //        this.controller.actionPerformed(evt);
    }//GEN-LAST:event_newUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agenda;
    private javax.swing.JLabel agendamentoTxt;
    private javax.swing.JButton agendar_bt;
    private javax.swing.JLabel bg_footer;
    private javax.swing.JLabel bg_left;
    private javax.swing.JLabel bg_main;
    private javax.swing.JLabel bg_main1;
    private javax.swing.JLabel bg_main2;
    private javax.swing.JButton cancelButtonAgenda;
    private javax.swing.JPanel center;
    private javax.swing.JButton clientButton;
    private javax.swing.JComboBox<String> cliente_cb;
    private javax.swing.JLabel cliente_txt;
    private javax.swing.JFormattedTextField dataFtf;
    private javax.swing.JLabel data_txt;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JButton exitButtonFooter;
    private javax.swing.JButton financesButton;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel gerenciaTxt;
    private javax.swing.JFormattedTextField hora_ftf;
    private javax.swing.JLabel hora_txt;
    private javax.swing.JTextField id_tf;
    private javax.swing.JLabel id_txt;
    private javax.swing.JLabel id_txt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel left;
    private javax.swing.JScrollPane listUsers;
    private javax.swing.JTable listaCliente_tb;
    private javax.swing.JTable listaCliente_tb1;
    private javax.swing.JButton logoutButtonFooter;
    private javax.swing.JPanel main;
    private javax.swing.JButton newButton;
    private javax.swing.JButton newUserButton;
    private javax.swing.JTextArea observTxtArea;
    private javax.swing.JButton reportButton;
    private javax.swing.JButton serviceButton;
    private javax.swing.JComboBox<String> servico_cb;
    private javax.swing.JLabel servico_txt;
    private javax.swing.JLabel title;
    private javax.swing.JLabel tituloTabelaTxt;
    private javax.swing.JButton updateUserButton;
    private javax.swing.JButton userButton;
    private javax.swing.JPanel users;
    private javax.swing.JTextField valorTf;
    private javax.swing.JLabel valor_txt;
    // End of variables declaration//GEN-END:variables

    
    public JPanel getAgenda() {
        return agenda;
    }

    public void setAgenda(JPanel agenda) {
        this.agenda = agenda;
    }

    public JButton getAgendar_bt() {
        return agendar_bt;
    }

    public void setAgendar_bt(JButton agendar_bt) {
        this.agendar_bt = agendar_bt;
    }

    public JButton getCancelButtonAgenda() {
        return cancelButtonAgenda;
    }

    public void setCancelButtonAgenda(JButton cancelButtonAgenda) {
        this.cancelButtonAgenda = cancelButtonAgenda;
    }

    public JButton getClientButton() {
        return clientButton;
    }

    public void setClientButton(JButton clientButton) {
        this.clientButton = clientButton;
    }

    public JComboBox<String> getCliente_cb() {
        return cliente_cb;
    }

    public void setCliente_cb(JComboBox<String> cliente_cb) {
        this.cliente_cb = cliente_cb;
    }

    public JFormattedTextField getDataFtf() {
        return dataFtf;
    }

    public void setDataFtf(JFormattedTextField dataFtf) {
        this.dataFtf = dataFtf;
    }

    public JButton getFinancesButton() {
        return financesButton;
    }

    public void setFinancesButton(JButton financesButton) {
        this.financesButton = financesButton;
    }

    public JFormattedTextField getHora_ftf() {
        return hora_ftf;
    }

    public void setHora_ftf(JFormattedTextField hora_ftf) {
        this.hora_ftf = hora_ftf;
    }

    public JTextField getId_tf() {
        return id_tf;
    }

    public void setId_tf(JTextField id_tf) {
        this.id_tf = id_tf;
    }

    public JLabel getId_txt1() {
        return id_txt1;
    }

    public void setId_txt1(JLabel id_txt1) {
        this.id_txt1 = id_txt1;
    }

    public JTable getListaCliente_tb() {
        return listaCliente_tb;
    }

    public void setListaCliente_tb(JTable listaCliente_tb) {
        this.listaCliente_tb = listaCliente_tb;
    }

    public JTable getListaCliente_tb1() {
        return listaCliente_tb1;
    }

    public void setListaCliente_tb1(JTable listaCliente_tb1) {
        this.listaCliente_tb1 = listaCliente_tb1;
    }

    public JPanel getMain() {
        return main;
    }

    public void setMain(JPanel main) {
        this.main = main;
    }

    public JButton getNewButton() {
        return newButton;
    }

    public void setNewButton(JButton newButton) {
        this.newButton = newButton;
    }

    public JTextArea getObservTxtArea() {
        return observTxtArea;
    }

    public void setObservTxtArea(JTextArea observTxtArea) {
        this.observTxtArea = observTxtArea;
    }

    public JButton getReportButton() {
        return reportButton;
    }

    public void setReportButton(JButton reportButton) {
        this.reportButton = reportButton;
    }

    public JButton getServiceButton() {
        return serviceButton;
    }

    public void setServiceButton(JButton serviceButton) {
        this.serviceButton = serviceButton;
    }

    public JComboBox<String> getServico_cb() {
        return servico_cb;
    }

    public void setServico_cb(JComboBox<String> servico_cb) {
        this.servico_cb = servico_cb;
    }

    public JButton getUserButton() {
        return userButton;
    }

    public void setUserButton(JButton userButton) {
        this.userButton = userButton;
    }

    public JPanel getUsuarios() {
        return users;
    }

    public void setUsuarios(JPanel usuarios) {
        this.users = usuarios;
    }

    public JTextField getValorTf() {
        return valorTf;
    }

    public void setValorTf(JTextField valorTf) {
        this.valorTf = valorTf;
    }

    public JButton getExitButtonFooter() {
        return exitButtonFooter;
    }

    public void setExitButtonFooter(JButton exitButtonFooter) {
        this.exitButtonFooter = exitButtonFooter;
    }

    public JButton getLogoutButtonFooter() {
        return logoutButtonFooter;
    }

    public void setLogoutButtonFooter(JButton logoutButtonFooter) {
        this.logoutButtonFooter = logoutButtonFooter;
    }

}
