/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.RegisterUserController;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Marina Savitzki
 */
public class RegisterUser extends javax.swing.JDialog {

    private final RegisterUserController controller;

    /**
     * Creates new form AuxView
     * @param parent
     * @param modal
     */
    public RegisterUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
         this.controller = new RegisterUserController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        userName1 = new javax.swing.JTextField();
        usuarioConfirm = new javax.swing.JLabel();
        userNameConfirm = new javax.swing.JTextField();
        senha = new javax.swing.JLabel();
        userPassword1 = new javax.swing.JPasswordField();
        senhaConfirm = new javax.swing.JLabel();
        userPasswordConfirm = new javax.swing.JPasswordField();
        registerUserButton = new javax.swing.JButton();
        cancelRegisterUserButton = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 51, 51));
        titulo.setText("Cadastro de usuário");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 440, 30));

        usuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        usuario.setForeground(new java.awt.Color(51, 51, 51));
        usuario.setText("Informe um usuário");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 430, 30));

        userName1.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        userName1.setMinimumSize(new java.awt.Dimension(6, 20));
        userName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName1ActionPerformed(evt);
            }
        });
        getContentPane().add(userName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 440, 40));

        usuarioConfirm.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        usuarioConfirm.setForeground(new java.awt.Color(51, 51, 51));
        usuarioConfirm.setText("Confirme o usuário");
        getContentPane().add(usuarioConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 430, 30));

        userNameConfirm.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        userNameConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(userNameConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 440, 40));

        senha.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        senha.setForeground(new java.awt.Color(51, 51, 51));
        senha.setText("Informe uma senha");
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 430, 30));

        userPassword1.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        getContentPane().add(userPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 440, 40));

        senhaConfirm.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        senhaConfirm.setForeground(new java.awt.Color(51, 51, 51));
        senhaConfirm.setText("Confirme sua senha");
        getContentPane().add(senhaConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 430, 30));

        userPasswordConfirm.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        getContentPane().add(userPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 440, 40));

        registerUserButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        registerUserButton.setText("Cadastrar");
        registerUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 200, 50));

        cancelRegisterUserButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cancelRegisterUserButton.setText("Cancelar");
        getContentPane().add(cancelRegisterUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 200, 50));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseMenor.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userName1ActionPerformed

    private void userNameConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameConfirmActionPerformed

    private void registerUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserButtonActionPerformed
        this.controller.actionPerformed(evt);
    }//GEN-LAST:event_registerUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterUser dialog = new RegisterUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton cancelRegisterUserButton;
    private javax.swing.JButton registerUserButton;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel senhaConfirm;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField userName1;
    private javax.swing.JTextField userNameConfirm;
    private javax.swing.JPasswordField userPassword1;
    private javax.swing.JPasswordField userPasswordConfirm;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuarioConfirm;
    // End of variables declaration//GEN-END:variables

    public JButton getCancelRegisterUserButton() {
        return cancelRegisterUserButton;
    }

    public void setCancelRegisterUserButton(JButton cancelRegisterUserButton) {
        this.cancelRegisterUserButton = cancelRegisterUserButton;
    }

    public JButton getRegisterUserButton() {
        return registerUserButton;
    }

    public void setRegisterUserButton(JButton registerUserButton) {
        this.registerUserButton = registerUserButton;
    }

    public JTextField getUserName1() {
        return userName1;
    }

    public void setUserName1(JTextField userName1) {
        this.userName1 = userName1;
    }

    public JTextField getUserNameConfirm() {
        return userNameConfirm;
    }

    public void setUserNameConfirm(JTextField userNameConfirm) {
        this.userNameConfirm = userNameConfirm;
    }

    public JPasswordField getUserPassword1() {
        return userPassword1;
    }

    public void setUserPassword1(JPasswordField userPassword1) {
        this.userPassword1 = userPassword1;
    }

    public JPasswordField getUserPasswordConfirm() {
        return userPasswordConfirm;
    }

    public void setUserPasswordConfirm(JPasswordField userPasswordConfirm) {
        this.userPasswordConfirm = userPasswordConfirm;
    }

    
}
